spring:
  application:
    name: git-repo-inspector
  Jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    apiversion:
      use:
        header: X-API-Version
      supported:
        - 1
      default: 1

server:
  port: 8080

github:
  baseurl: "https://api.github.com"
  version: "2026-03-10"
